# Generated by Django 2.2.1 on 2019-06-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliq_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.CharField(max_length=30)),
                ('followee', models.CharField(max_length=30)),
            ],
        ),
    ]
