# Generated by Django 2.2.1 on 2019-06-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliq_backend', '0002_follows'),
    ]

    operations = [
        migrations.AddField(
            model_name='follows',
            name='fstatus',
            field=models.CharField(default='requested', max_length=10),
            preserve_default=False,
        ),
    ]
