# Generated by Django 2.2.1 on 2019-06-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliq_backend', '0003_follows_fstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='privacy',
            field=models.CharField(default='private', max_length=30),
        ),
    ]
