# Generated by Django 2.2.1 on 2019-06-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliq_backend', '0004_user_privacy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageId', models.IntegerField()),
                ('username', models.CharField(max_length=30)),
            ],
        ),
    ]
